title: Akis Mylordos
logo: /assets/img/headshot_circle.png
description: Seasoned professional with 6+ years of experience in the Data/BI engineering landscape at a world-leading firm.
#show_downloads: true
theme: jekyll-theme-minimal
