title: Akis Mylordos
logo: /assets/img/headshot_circle.png
description: Seasoned professional with over 6 years of experience in the data/BI landscape at a world leading firm
#show_downloads: true
theme: jekyll-theme-minimal
